/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ProveapiCore } from "../core.js";
import { encodeBodyForm as encodeBodyForm$ } from "../lib/encodings.js";
import * as m$ from "../lib/matchers.js";
import * as schemas$ from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import {
    ConnectionError,
    InvalidRequestError,
    RequestAbortedError,
    RequestTimeoutError,
    UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { SDKError } from "../models/errors/sdkerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { Result } from "../types/fp.js";

/**
 * Request OAuth token.
 *
 * @remarks
 * Send this request to request the OAuth token.
 */
export async function v3V3TokenRequest(
    client$: ProveapiCore,
    request?: components.V3TokenRequest | undefined,
    options?: RequestOptions
): Promise<
    Result<
        operations.V3TokenRequestResponse,
        | errors.ErrorT
        | SDKError
        | SDKValidationError
        | UnexpectedClientError
        | InvalidRequestError
        | RequestAbortedError
        | RequestTimeoutError
        | ConnectionError
    >
> {
    const input$ = request;

    const parsed$ = schemas$.safeParse(
        input$,
        (value$) => components.V3TokenRequest$outboundSchema.optional().parse(value$),
        "Input validation failed"
    );
    if (!parsed$.ok) {
        return parsed$;
    }
    const payload$ = parsed$.value;
    const body$ = Object.entries(payload$ || {})
        .map(([k, v]) => {
            return encodeBodyForm$(k, v, { charEncoding: "percent" });
        })
        .join("&");

    const path$ = pathToFunc("/token")();

    const headers$ = new Headers({
        "Content-Type": "application/x-www-form-urlencoded",
        Accept: "application/json",
    });

    const context = { operationID: "V3TokenRequest", oAuth2Scopes: [], securitySource: null };

    const requestRes = client$.createRequest$(
        context,
        {
            method: "POST",
            path: path$,
            headers: headers$,
            body: body$,
            timeoutMs: options?.timeoutMs || client$.options$.timeoutMs || -1,
        },
        options
    );
    if (!requestRes.ok) {
        return requestRes;
    }
    const request$ = requestRes.value;

    const doResult = await client$.do$(request$, {
        context,
        errorCodes: ["400", "4XX", "500", "5XX"],
        retryConfig: options?.retries || client$.options$.retryConfig,
        retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
    });
    if (!doResult.ok) {
        return doResult;
    }
    const response = doResult.value;

    const responseFields$ = {
        HttpMeta: { Response: response, Request: request$ },
    };

    const [result$] = await m$.match<
        operations.V3TokenRequestResponse,
        | errors.ErrorT
        | SDKError
        | SDKValidationError
        | UnexpectedClientError
        | InvalidRequestError
        | RequestAbortedError
        | RequestTimeoutError
        | ConnectionError
    >(
        m$.json(200, operations.V3TokenRequestResponse$inboundSchema, { key: "V3TokenResponse" }),
        m$.jsonErr([400, 500], errors.ErrorT$inboundSchema),
        m$.fail(["4XX", "5XX"])
    )(response, request$, { extraFields: responseFields$ });
    if (!result$.ok) {
        return result$;
    }

    return result$;
}
