/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { V3 } from "./v3.js";

export class Proveapi extends ClientSDK {
  private _v3?: V3;
  get v3(): V3 {
    return (this._v3 ??= new V3(this._options));
  }
}
