/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type V3ChallengeRequestResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successful request.
     */
    v3ChallengeResponse?: components.V3ChallengeResponse | undefined;
};

/** @internal */
export namespace V3ChallengeRequestResponse$ {
    export const inboundSchema: z.ZodType<V3ChallengeRequestResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            V3ChallengeResponse: components.V3ChallengeResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.V3ChallengeResponse === undefined
                    ? null
                    : { v3ChallengeResponse: v.V3ChallengeResponse }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        V3ChallengeResponse?: components.V3ChallengeResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V3ChallengeRequestResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            v3ChallengeResponse: components.V3ChallengeResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.v3ChallengeResponse === undefined
                    ? null
                    : { V3ChallengeResponse: v.v3ChallengeResponse }),
            };
        });
}
