/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type V3ValidateRequestResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successful request.
     */
    v3ValidateResponse?: components.V3ValidateResponse | undefined;
};

/** @internal */
export namespace V3ValidateRequestResponse$ {
    export const inboundSchema: z.ZodType<V3ValidateRequestResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            V3ValidateResponse: components.V3ValidateResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.V3ValidateResponse === undefined
                    ? null
                    : { v3ValidateResponse: v.V3ValidateResponse }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        V3ValidateResponse?: components.V3ValidateResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V3ValidateRequestResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            v3ValidateResponse: components.V3ValidateResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.v3ValidateResponse === undefined
                    ? null
                    : { V3ValidateResponse: v.v3ValidateResponse }),
            };
        });
}
