/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type AddressEntry = {
    /**
     * Address is the street address of the individual.
     */
    address?: string | undefined;
    /**
     * City of the individual.
     */
    city?: string | undefined;
    /**
     * Extended address is the apartment number or other extended address information.
     */
    extendedAddress?: string | undefined;
    /**
     * Postal code is the zip code of the individual.
     */
    postalCode?: string | undefined;
    /**
     * Region is the state or locality of the individual.
     */
    region?: string | undefined;
};

/** @internal */
export namespace AddressEntry$ {
    export const inboundSchema: z.ZodType<AddressEntry, z.ZodTypeDef, unknown> = z
        .object({
            address: z.string().optional(),
            city: z.string().optional(),
            extendedAddress: z.string().optional(),
            postalCode: z.string().optional(),
            region: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.address === undefined ? null : { address: v.address }),
                ...(v.city === undefined ? null : { city: v.city }),
                ...(v.extendedAddress === undefined
                    ? null
                    : { extendedAddress: v.extendedAddress }),
                ...(v.postalCode === undefined ? null : { postalCode: v.postalCode }),
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });

    export type Outbound = {
        address?: string | undefined;
        city?: string | undefined;
        extendedAddress?: string | undefined;
        postalCode?: string | undefined;
        region?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddressEntry> = z
        .object({
            address: z.string().optional(),
            city: z.string().optional(),
            extendedAddress: z.string().optional(),
            postalCode: z.string().optional(),
            region: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.address === undefined ? null : { address: v.address }),
                ...(v.city === undefined ? null : { city: v.city }),
                ...(v.extendedAddress === undefined
                    ? null
                    : { extendedAddress: v.extendedAddress }),
                ...(v.postalCode === undefined ? null : { postalCode: v.postalCode }),
                ...(v.region === undefined ? null : { region: v.region }),
            };
        });
}
