/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AdverseMediaResponseInternal = {
    date?: string | undefined;
    snippet?: string | undefined;
    title?: string | undefined;
    url?: string | undefined;
};

/** @internal */
export const AdverseMediaResponseInternal$inboundSchema: z.ZodType<
    AdverseMediaResponseInternal,
    z.ZodTypeDef,
    unknown
> = z.object({
    date: z.string().optional(),
    snippet: z.string().optional(),
    title: z.string().optional(),
    url: z.string().optional(),
});

/** @internal */
export type AdverseMediaResponseInternal$Outbound = {
    date?: string | undefined;
    snippet?: string | undefined;
    title?: string | undefined;
    url?: string | undefined;
};

/** @internal */
export const AdverseMediaResponseInternal$outboundSchema: z.ZodType<
    AdverseMediaResponseInternal$Outbound,
    z.ZodTypeDef,
    AdverseMediaResponseInternal
> = z.object({
    date: z.string().optional(),
    snippet: z.string().optional(),
    title: z.string().optional(),
    url: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AdverseMediaResponseInternal$ {
    /** @deprecated use `AdverseMediaResponseInternal$inboundSchema` instead. */
    export const inboundSchema = AdverseMediaResponseInternal$inboundSchema;
    /** @deprecated use `AdverseMediaResponseInternal$outboundSchema` instead. */
    export const outboundSchema = AdverseMediaResponseInternal$outboundSchema;
    /** @deprecated use `AdverseMediaResponseInternal$Outbound` instead. */
    export type Outbound = AdverseMediaResponseInternal$Outbound;
}
