/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type DataSource = {
    address?: string | undefined;
    cipConfidence?: string | undefined;
    email?: string | undefined;
    identifiers?: string | undefined;
    name?: string | undefined;
    reasonCodes?: Array<string> | undefined;
    verified?: boolean | undefined;
};

/** @internal */
export namespace DataSource$ {
    export const inboundSchema: z.ZodType<DataSource, z.ZodTypeDef, unknown> = z.object({
        address: z.string().optional(),
        cipConfidence: z.string().optional(),
        email: z.string().optional(),
        identifiers: z.string().optional(),
        name: z.string().optional(),
        reasonCodes: z.array(z.string()).optional(),
        verified: z.boolean().optional(),
    });

    export type Outbound = {
        address?: string | undefined;
        cipConfidence?: string | undefined;
        email?: string | undefined;
        identifiers?: string | undefined;
        name?: string | undefined;
        reasonCodes?: Array<string> | undefined;
        verified?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DataSource> = z.object({
        address: z.string().optional(),
        cipConfidence: z.string().optional(),
        email: z.string().optional(),
        identifiers: z.string().optional(),
        name: z.string().optional(),
        reasonCodes: z.array(z.string()).optional(),
        verified: z.boolean().optional(),
    });
}
