/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type EmailAddressResponse = {
    /**
     * A boolean value indicating if the email address was matched during processing.
     */
    emailAddress?: boolean | undefined;
};

/** @internal */
export namespace EmailAddressResponse$ {
    export const inboundSchema: z.ZodType<EmailAddressResponse, z.ZodTypeDef, unknown> = z.object({
        emailAddress: z.boolean().optional(),
    });

    export type Outbound = {
        emailAddress?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EmailAddressResponse> = z.object(
        {
            emailAddress: z.boolean().optional(),
        }
    );
}
