/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AddressEntry, AddressEntry$ } from "./addressentry";
import * as z from "zod";

export type Individual = {
    /**
     * Addresses that belong to the individual.
     */
    addresses?: Array<AddressEntry> | undefined;
    /**
     * DOB is the date of birth of the individual.
     */
    dob?: string | undefined;
    /**
     * Email addresses that belong to the individual.
     */
    emailAddresses?: Array<string> | undefined;
    /**
     * First name of the individual.
     */
    firstName?: string | undefined;
    /**
     * Las name of the individual.
     */
    lastName?: string | undefined;
    /**
     * SSN is the social security number of the individual.
     */
    ssn?: string | undefined;
};

/** @internal */
export namespace Individual$ {
    export const inboundSchema: z.ZodType<Individual, z.ZodTypeDef, unknown> = z
        .object({
            addresses: z.array(AddressEntry$.inboundSchema).optional(),
            dob: z.string().default("2024-05-02 00:00:00 +0000 UTC"),
            emailAddresses: z.array(z.string()).optional(),
            firstName: z.string().default("Tod"),
            lastName: z.string().default("Weedall"),
            ssn: z.string().default("265228370"),
        })
        .transform((v) => {
            return {
                ...(v.addresses === undefined ? null : { addresses: v.addresses }),
                dob: v.dob,
                ...(v.emailAddresses === undefined ? null : { emailAddresses: v.emailAddresses }),
                firstName: v.firstName,
                lastName: v.lastName,
                ssn: v.ssn,
            };
        });

    export type Outbound = {
        addresses?: Array<AddressEntry$.Outbound> | undefined;
        dob: string;
        emailAddresses?: Array<string> | undefined;
        firstName: string;
        lastName: string;
        ssn: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Individual> = z
        .object({
            addresses: z.array(AddressEntry$.outboundSchema).optional(),
            dob: z.string().default("2024-05-02 00:00:00 +0000 UTC"),
            emailAddresses: z.array(z.string()).optional(),
            firstName: z.string().default("Tod"),
            lastName: z.string().default("Weedall"),
            ssn: z.string().default("265228370"),
        })
        .transform((v) => {
            return {
                ...(v.addresses === undefined ? null : { addresses: v.addresses }),
                dob: v.dob,
                ...(v.emailAddresses === undefined ? null : { emailAddresses: v.emailAddresses }),
                firstName: v.firstName,
                lastName: v.lastName,
                ssn: v.ssn,
            };
        });
}
