/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    V3ChallengeAddressEntryRequest,
    V3ChallengeAddressEntryRequest$,
} from "./v3challengeaddressentryrequest";
import * as z from "zod";

export type V3ChallengeIndividualRequest = {
    /**
     * Addresses that belong to the individual.
     */
    addresses?: Array<V3ChallengeAddressEntryRequest> | undefined;
    /**
     * DOB is the date of birth of the individual.
     */
    dob?: string | undefined;
    /**
     * Email addresses that belong to the individual.
     */
    emailAddresses?: Array<string> | undefined;
    /**
     * First name of the individual.
     */
    firstName?: string | undefined;
    /**
     * Last name of the individual.
     */
    lastName?: string | undefined;
    /**
     * SSN is the social security number of the individual.
     */
    ssn?: string | undefined;
};

/** @internal */
export namespace V3ChallengeIndividualRequest$ {
    export const inboundSchema: z.ZodType<V3ChallengeIndividualRequest, z.ZodTypeDef, unknown> =
        z.object({
            addresses: z.array(V3ChallengeAddressEntryRequest$.inboundSchema).optional(),
            dob: z.string().optional(),
            emailAddresses: z.array(z.string()).optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            ssn: z.string().optional(),
        });

    export type Outbound = {
        addresses?: Array<V3ChallengeAddressEntryRequest$.Outbound> | undefined;
        dob?: string | undefined;
        emailAddresses?: Array<string> | undefined;
        firstName?: string | undefined;
        lastName?: string | undefined;
        ssn?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V3ChallengeIndividualRequest> =
        z.object({
            addresses: z.array(V3ChallengeAddressEntryRequest$.outboundSchema).optional(),
            dob: z.string().optional(),
            emailAddresses: z.array(z.string()).optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            ssn: z.string().optional(),
        });
}
