/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V3CompleteAddressEntryRequest,
    V3CompleteAddressEntryRequest$inboundSchema,
    V3CompleteAddressEntryRequest$Outbound,
    V3CompleteAddressEntryRequest$outboundSchema,
} from "./v3completeaddressentryrequest.js";
import * as z from "zod";

export type V3CompleteIndividualRequest = {
    /**
     * Addresses that belong to the individual.
     */
    addresses?: Array<V3CompleteAddressEntryRequest> | undefined;
    /**
     * DOB is the date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
     */
    dob?: string | undefined;
    /**
     * Email addresses that belong to the individual.
     */
    emailAddresses?: Array<string> | undefined;
    /**
     * First name of the individual.
     */
    firstName?: string | undefined;
    /**
     * Last4SSN is last 4 digits of SSN.
     */
    last4SSN?: string | undefined;
    /**
     * Last name of the individual.
     */
    lastName?: string | undefined;
    /**
     * SSN is the social security number of the individual.
     */
    ssn?: string | undefined;
};

/** @internal */
export const V3CompleteIndividualRequest$inboundSchema: z.ZodType<
    V3CompleteIndividualRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    addresses: z.array(V3CompleteAddressEntryRequest$inboundSchema).optional(),
    dob: z.string().optional(),
    emailAddresses: z.array(z.string()).optional(),
    firstName: z.string().optional(),
    last4SSN: z.string().optional(),
    lastName: z.string().optional(),
    ssn: z.string().optional(),
});

/** @internal */
export type V3CompleteIndividualRequest$Outbound = {
    addresses?: Array<V3CompleteAddressEntryRequest$Outbound> | undefined;
    dob?: string | undefined;
    emailAddresses?: Array<string> | undefined;
    firstName?: string | undefined;
    last4SSN?: string | undefined;
    lastName?: string | undefined;
    ssn?: string | undefined;
};

/** @internal */
export const V3CompleteIndividualRequest$outboundSchema: z.ZodType<
    V3CompleteIndividualRequest$Outbound,
    z.ZodTypeDef,
    V3CompleteIndividualRequest
> = z.object({
    addresses: z.array(V3CompleteAddressEntryRequest$outboundSchema).optional(),
    dob: z.string().optional(),
    emailAddresses: z.array(z.string()).optional(),
    firstName: z.string().optional(),
    last4SSN: z.string().optional(),
    lastName: z.string().optional(),
    ssn: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CompleteIndividualRequest$ {
    /** @deprecated use `V3CompleteIndividualRequest$inboundSchema` instead. */
    export const inboundSchema = V3CompleteIndividualRequest$inboundSchema;
    /** @deprecated use `V3CompleteIndividualRequest$outboundSchema` instead. */
    export const outboundSchema = V3CompleteIndividualRequest$outboundSchema;
    /** @deprecated use `V3CompleteIndividualRequest$Outbound` instead. */
    export type Outbound = V3CompleteIndividualRequest$Outbound;
}
