/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

export type V3TokenRequest = {
    /**
     * ClientID is the optional client ID.
     */
    clientId?: string | undefined;
    /**
     * ClientSecret is the client secret ID provided to the customer during onboarding.
     */
    clientSecret?: string | undefined;
    /**
     * GrantType only allows option: `client_credentials`.
     */
    grantType: string;
};

/** @internal */
export namespace V3TokenRequest$ {
    export const inboundSchema: z.ZodType<V3TokenRequest, z.ZodTypeDef, unknown> = z
        .object({
            client_id: z.string().optional(),
            client_secret: z.string().optional(),
            grant_type: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                client_id: "clientId",
                client_secret: "clientSecret",
                grant_type: "grantType",
            });
        });

    export type Outbound = {
        client_id?: string | undefined;
        client_secret?: string | undefined;
        grant_type: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V3TokenRequest> = z
        .object({
            clientId: z.string().optional(),
            clientSecret: z.string().optional(),
            grantType: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                clientId: "client_id",
                clientSecret: "client_secret",
                grantType: "grant_type",
            });
        });
}
