/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type V3ValidateRequest = {
    /**
     * Correlation ID is the unique ID of the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow.
     */
    correlationId?: string | undefined;
};

/** @internal */
export namespace V3ValidateRequest$ {
    export const inboundSchema: z.ZodType<V3ValidateRequest, z.ZodTypeDef, unknown> = z
        .object({
            correlationId: z.string().default("713189b8-5555-4b08-83ba-75d08780aebd"),
        })
        .transform((v) => {
            return {
                correlationId: v.correlationId,
            };
        });

    export type Outbound = {
        correlationId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V3ValidateRequest> = z
        .object({
            correlationId: z.string().default("713189b8-5555-4b08-83ba-75d08780aebd"),
        })
        .transform((v) => {
            return {
                correlationId: v.correlationId,
            };
        });
}
